[Feature] Search form
dh-center/st-retrospect-frontend pull request #107
Opened 2021-04-04 19:27 UTC by Xemka

2021-04-04 19:52 UTC, ilyamore88 requested changes

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +            });
Можно заменить на 
```
if (!onChange) return;
```

2021-04-04 19:52 UTC, ilyamore88 commented on src/interfaces/SearchProps.tsx
> +export interface SearchProps {
Кажется, надо запилить отдельный интерфейс для SearchFormState. В нём у тебя будет 
```
query: "Это запрос из инпута",
filters: {
  categories: [] // тут у тебя категории из селекта
  years: {
    left: 10,
    right: 20,
  }
}
```

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +function YearsInputs(props: SearchProps): ReactElement {
Не используй тут SearchProps, у каждого компонента свой интерфейс пропов. Если у тебя одинаковые пропы в YearsInputs и CustomRange, то это должен быть интерфейс с осознанным названием типа `YearsFilterProps`.

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +    right: props.max });
Лишнее

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/asides/MainAside.tsx
> +                right={'1900'}
Этого тут быть не должно

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/SearchForm.tsx
> +    right: props.right });
Нужно более осознанное название, а не values. Непонятно, за что они отвечают

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/CustomRange.tsx
>          value={values.left}
Пофиксить

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/CustomRange.tsx
> +    right: props.right });
Лишнее

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/CustomRange.tsx
> +  const onChange = props.onChange;
Такое делать не обязательно. Лучше даже наверно оставлять `props.onChange` для наглядности.

2021-04-04 19:52 UTC, ilyamore88 commented on src/interfaces/SearchProps.tsx
> +export interface SearchProps {
Помню, что мы хотели прокидывать данные через submit event. Но я подумал, кажется можно запилить вот такой стейт, который намного структурированнее и приятнее, чем то, что у нас выйдет в submit.

2021-04-04 19:52 UTC, ilyamore88 commented on src/interfaces/SearchProps.tsx
> +export interface SearchProps {
Да и с таким работать будет попроще. Например, можно такой объект прокидывать куда хочешь

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/SearchForm.tsx
> +const SearchWrapper = styled.div``;
А это что. Если стилей нет, то нет смысла такое делать. И вообще, есть такая штука как 
```
return (
  <>
  ...
  </>
);
```
Можешь погуглить

2021-04-04 19:52 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +            });
Кажется, можно сделать 
```
onChange({
  ...props.values,
  left: value
});
```

2021-04-07 08:36 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +  }, [ props ]);
```suggestion
  }, [ props.left, props.right ]);
```

2021-04-07 08:36 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +  }, [ currentYearsValues ]);
А нельзя debounce использовать в инпуте, а не в useEffect?

2021-04-07 08:36 UTC, ilyamore88 commented on src/components/YearsInputs.tsx
> +  }, [ currentYearsValues ]);
Во всяком случае, сейчас это не работает. Если я не ошибаюсь, то debounce возвращает функцию, которую надо вызвать.

2021-04-07 20:33 UTC, ilyamore88 commented on src/utils/debounce.ts
> +/**
Если не используешь debounce, то убери из реквеста

2021-04-11 20:31 UTC, ilyamore88 commented on src/components/CustomSelect.tsx
> +function CustomSelect(change: OnChangeSelected, props: WithClassName): ReactElement {
А почему нельзя было change добавлять в props?

2021-04-11 20:31 UTC, ilyamore88 commented on src/components/CustomSelect.tsx
> +function CustomSelect(change: OnChangeSelected, props: WithClassName): ReactElement {
Через extends какой-нибудь

2021-04-12 11:27 UTC, nikmel2803 requested changes

2021-04-12 11:27 UTC, nikmel2803 commented on src/components/CustomSelect.tsx
> +function CustomSelect(change: OnChangeSelected, props: WithClassName): ReactElement {
почему тут вообще два аргумента? пропсы передаются только в первом аргументе. Второй для ref

2021-04-12 11:27 UTC, nikmel2803 commented on src/components/CustomSelect.tsx
> +  }, [ selected ]);
может убрать отсюда selected? вынести его в пропсы, как это обычно и делается для всех инпутов. В пропсах будет `selected: string[], onChange(value: string[]): void`. И useEffect не нужен будет.

2021-04-12 11:27 UTC, nikmel2803 commented on src/components/YearsInputs.tsx
> +  }, [props.left, props.right]);
аналогично. Давай не хранить текущий стейт в компоненте

2021-04-12 11:27 UTC, nikmel2803 commented on src/components/YearsInputs.tsx
> +  let rangeUpdateTimeout: ReturnType<typeof setTimeout>;
что-то с таймаутом как-то сложно
может просто debounce? https://www.npmjs.com/package/lodash.debounce

2021-04-12 11:27 UTC, nikmel2803 commented on src/components/YearsInputs.tsx
> +  let rangeUpdateTimeout: ReturnType<typeof setTimeout>;
есть ещё идея обновлять инпут не по таймеру, а по выходу из фокуса 🤔

2021-04-12 11:27 UTC, nikmel2803 commented on src/interfaces/searchForm/OnChangeSelected.tsx
> +export interface OnChangeSelected {
вообще, у нас пропсы обычно лежат там же, где и компонент (в том же файле). Я не вижу особого смысла выносить их отдельно

2021-04-12 11:58 UTC, Xemka commented on src/components/CustomSelect.tsx
> +  }, [ selected ]);
пропсы Илья комментил уже, исправил
selected перенесу

2021-04-13 15:02 UTC, Xemka commented on src/components/YearsInputs.tsx
> +  let rangeUpdateTimeout: ReturnType<typeof setTimeout>;
@nikmel2803 я думаю при обычном использовании эти блоки будут изменяться в последний момент и момент потери фокуса совпадет с нажатием на кнопку поиска, то есть пользователь будет вводить инфу в поля, а слайдеры будут стоять и сдвинутся скорее всего только после нажатия на поиск. Возможно пользователь таки нажмет на пустоту или другой блок, но я думаю наврядли т.к. это самый нижний компонент и его он будет трогать в последний момент

2021-04-15 14:17 UTC, ilyamore88 commented
Deprecated

2021-04-15 14:17 UTC, closed without merging