[Feature] Menu items
dh-center/st-retrospect-frontend pull request #119
Opened 2021-04-28 07:29 UTC by Xemka

2021-04-28 07:44 UTC, ilyamore88 requested changes
Лучше вместо передачи номеров пунктов меню завести enum

2021-04-28 07:44 UTC, ilyamore88 commented on package.json
> +    "file-loader": "^6.2.0",
Зачем это

2021-04-28 07:44 UTC, ilyamore88 commented on src/components/Menu.tsx
> +interface MenuInputProps {
Нет дока

2021-04-28 07:44 UTC, ilyamore88 commented on src/components/Menu.tsx
> +   * onChange event handler
Так onChange или onClick? Для onClick есть интерфейс `WithOnClick`, только там надо будет добавить необязательный параметр.

2021-04-28 07:44 UTC, ilyamore88 commented on src/components/Menu.tsx
> +   * onChange event handler
Зачем тебе оно вообще нужно, если ты используешь контекст?

2021-04-28 07:44 UTC, ilyamore88 commented on src/components/MenuContent.tsx
> +interface MenuContentProps extends WithChildren {
Нет дока

2021-04-28 07:44 UTC, ilyamore88 commented on src/components/MenuContent.tsx
> +  numberOfSelectedMenuItem: number;
Зачем тебе здесь номер? Можно сделать проп `isShow: boolean`

2021-04-28 07:44 UTC, ilyamore88 commented on src/components/asides/MainAside.tsx
> +  function SelectedMenuItem(props: Num): ReactElement {
Функция в функции? Это надо выносить

2021-04-28 07:45 UTC, ilyamore88 commented on src/components/asides/MainAside.tsx
> +  function SelectedMenuItem(props: Num): ReactElement {
Либо сделать что-то типа 
```
const selectedMenuItem = () => {
  enum...
    return <></>
}
```

2021-04-28 07:45 UTC, ilyamore88 commented on src/components/asides/MainAside.tsx
> +  function SelectedMenuItem(props: Num): ReactElement {
Ну и дока нет

2021-05-04 18:59 UTC, nikmel2803 commented on src/custom.d.ts
> +
это где-то описано в доках? может сюда ссылочку впихнуть?

2021-05-04 18:59 UTC, nikmel2803 commented on src/components/menuContent/AboutProject.tsx
> +        <br/><br/>
вообще говоря, лучше юзать параграфы и задавать отступы между ними. Более семантически верно

2021-05-04 18:59 UTC, nikmel2803 commented on src/components/asides/MenuAside.tsx
> +        return <OurPartners/>;
может было бы лучше через роутер?

2021-05-04 19:01 UTC, ilyamore88 commented on src/components/asides/MenuAside.tsx
> +        return <OurPartners/>;
Смысла мало, от этого, если честно

2021-05-04 19:03 UTC, ilyamore88 commented on src/custom.d.ts
> +
Не уверен, что это есть где-то в доках, я сделал это по аналогии с svg

2021-05-04 20:22 UTC, nikmel2803 approved these changes

2021-05-04 20:26 UTC, ilyamore88 approved these changes

2021-05-04 20:26 UTC, merged