Periods range component
dh-center/st-retrospect-frontend pull request #99
Opened 2021-03-24 19:23 UTC by Xemka

Added new component with custom range input with two sliders.
![image](https://user-images.githubusercontent.com/43967788/112371072-3f2e3f80-8cef-11eb-915a-7068b25ebcd7.png)
Based on VUE [version](https://github.com/dh-center/st-retrospect-frontend/pull/74).

2021-03-27 09:30 UTC, ilyamore88 requested changes

2021-03-27 09:30 UTC, ilyamore88 commented on src/components/CustomRange.tsx
> +      </RangeLabel>
Если не передать label, то блок будет пустым

2021-03-27 09:30 UTC, ilyamore88 commented on src/components/CustomRange.tsx
> +          }
```suggestion
            setValues({ 
              left: values.right,
              right: value.target.value 
            });
          } else {
            setValues({ 
              left: value.target.value,
              right: values.right 
            });
          }
```

2021-03-27 09:30 UTC, ilyamore88 commented on src/components/CustomRange.tsx
> +        }
Здесь тоже оформи как выше. Закрывать двойные скобки можно }}.

2021-03-27 09:30 UTC, ilyamore88 commented on src/components/asides/MainAside.tsx
> +          label={'years'}
Лучше передавать сюда t(), а не юзать его в компоненте.

2021-03-28 10:30 UTC, ilyamore88 approved these changes

2021-03-28 10:31 UTC, ilyamore88 approved these changes

2021-03-28 10:45 UTC, nikmel2803 approved these changes

2021-03-28 10:59 UTC, merged